### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by SophieDC98** [sayedmohamedscu/YOLO-v5-Door-detection-for-visually-impaired-people#1]
Hi,

I'm very much interested in your project! When are you planning to upload your code/model weights?

Thanks in advance!

**Comment by sayedmohamedscu** [comment]
Hello

It was a freelancing project I will ask the client if it's possible to
share it with you

Best regards

**Comment by handitan** [comment]
Hi sayedmohamedscu,
I am interested with this as well.
Would like to know if I could have access to it as well?

Thank you very much

**Comment by sayedmohamedscu** [comment]
I have uploaded the model and and a demo on hugging face

**Comment by sayedmohamedscu** [comment]
https://github.com/sayedmohamedscu/YOLOv8-Door-detection-for-visually-impaired-people

I have updated version with yolov8

@handitan @sophieDataroots
